#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#  fastd-genkey 0.1
#
#  Copyright 2015 Felix Kaechele <felix@freifunk-leverkusen.de>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#

import subprocess
import sys


def main():
    privkey = subprocess.check_output(["ecdsakeygen", "-s"])
    pubkey = subprocess.check_output(["ecdsakeygen", "-p"], input=privkey)
    print("# public key: {0}\nsecret \"{1}\";".format(
        pubkey.decode("utf-8").rstrip(), privkey.decode("utf-8").rstrip()))

if __name__ == '__main__':
    returnCode = main()
    sys.exit(returnCode)
