---
galaxy_info:
  author: kaleng
  description: setup fastd vpn
  license: GPLv3
  min_ansible_version: 1.8
  platforms:
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
  - networking
dependencies: []
