 ---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://docs.ansible.com/playbooks_intro.html for more information about handlers.
 
- name: Restart server
  command: shutdown -r now "Reboot triggered by Ansible"
  async: 0
  poll: 0
  ignore_errors: true
- name: Wait for server to restart
  local_action:
    module: wait_for
      host={{ inventory_hostname }}
      delay=1
      timeout=300
    sudo: false
